# Basic
title: William Xie's GameHub
subtitle: A CG Noob
welcome_message: <a href="https://github.com/GuardHei" target="_blank">Super Mario Bros. 2 Baby !</a>
description: Mario / Zelda / Darksouls Fan
# creator: <a href="http://onev.cat">@onevcat</a>

# url: "http://vno.onevcat.com"

permalink: /:year/:month/:title/

# Format
highlighter: blue

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: blue

# The blog button should not be removed.
blog_button:
    title: Blogs
    description: Visit My Blogs

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: Visit My Projects, url: 'https://github.com/GuardHei'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    # disqus: xzd
    
# Social
social:
    github: GuardHei
    mail: williamxie3421@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host

theme: jekyll-theme-architect