# Basic
title: 谢祖地 的 博客
subtitle: 请不要在意细节
welcome_message: <a href="https://github.com/GuardHei" target="_blank">嘿嘿嘿</a>
description: 这是一个 IB Survivor 写的博客
# creator: <a href="http://onev.cat">@onevcat</a>

# url: "http://vno.onevcat.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: blue

# The blog button should not be removed.
blog_button:
    title: Blog
    description: 访问我的博客

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: 访问我的项目, url: 'https://github.com/GuardHei'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    
# Social
social:
    github: https://github.com/GuardHei
    mail: williamxie3421@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
